name = "remote-control-app"
main = "workers/api.js"
account_id = "8bc23f112e6141aff6947950a5bb8445"
compatibility_date = "2025-07-01"

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "UPLOAD_KV"
id = "ae0033f3ec6f4be1bfb7009386436606"  # Remplace par l’ID réel de ta KV
